name: Deploy Garmin Lambda

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create deployment package directory
        run: |
          mkdir lambda_build
          cp garmin/garmin/scripts/lambda_update.py lambda_build/
          cp garmin/garmin/api.py lambda_build/
          cp garmin/garmin/updaters.py lambda_build/
          cp -r garmin/garmin/pullers lambda_build/
          cp -r garmin/garmin/db lambda_build/
          cp garmin/requirements-lambda.txt lambda_build/requirements.txt

      - name: Install dependencies
        run: |
          pip install -r lambda_build/requirements.txt -t lambda_build/

      - name: Zip deployment package
        run: |
          cd lambda_build
          zip -r ../lambda_deploy.zip .

      - name: Deploy to Lambda
        uses: appleboy/lambda-action@v0.1.9
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION || 'us-east-2' }}
          function_name: garmin-data-updater
          zip_file: lambda_deploy.zip
